### ISSUE TITLE
Error copy My_app_name_csync.dll

### ISSUE THREAD

**Issue by afprobst** [misch7/nextcloud-client-building#8]
Hello Michael! A few weeks ago I successfully generated my version by following your scripts and changing app_name to my name. Now the compilation gave an error and asked to update QT to version 5.15.2 and after that the dlls were not generated with my name. And now it stops with this cp error: cannot stat 'c:/Nextcloud/client-building/install/Release/Win64/bin/my_app_name_csync.dll': No such file or directory
Help!!!

**Comment by misch7** [comment]
Hello @afprobst, I'm not actively maintaining this repo anymore, the Desktop Team has taken it over. However, I've seen you have already opened an issue there too, although the response obviously didn't solve it.

Please also note that this repo here is outdated, so If you've tried to build with Qt 5.15.x it's likely the root cause.

Unfortunately I cannot make a sophisticated guess since I don't work with the builds anymore and haven't tried Qt 5.15.
